<a href="https://colab.research.google.com/github/Aubinrocky/SwimmingRecords/blob/main/SwimmingRecordsScrapingFemale.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
#Importation des modules
import requests
from bs4 import BeautifulSoup
import pandas as pd
import random
import time
import matplotlib.pyplot as plt
headers = {'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/37.0.2062.94 Chrome/37.0.2062.94 Safari/537.36'}

In [68]:
disciplines = ['50_mètres_nage_libre', '100_mètres_nage_libre','200_mètres_nage_libre','400_mètres_nage_libre','800_mètres_nage_libre','1500_mètres_nage_libre',
               '50_mètres_dos',
               '50_mètres_brasse','100_mètres_brasse','200_mètres_brasse',
               '50_mètres_papillon','100_mètres_papillon','200_mètres_papillon',
               '200_mètres_4_nages','400_mètres_4_nages']

In [69]:
dataset = []
for discipline in disciplines:
  time.sleep(0.8)
  url = 'https://fr.wikipedia.org/wiki/Record_du_monde_de_natation_dames_du_' + discipline
  response = requests.get(url, headers=headers)
  soup = BeautifulSoup(response.content, 'lxml')
  divs = soup.find_all("div", {"class":"mw-body-content mw-content-ltr"})
  div = divs[0]
  spans = div.find_all("span", {"class":"mw-headline"})
  tables = div.find_all("table", {"class" : "wikitable sortable"})
  
  #Bassin de 50 mètres
  trs50 = tables[0].tbody.find_all("tr")
  trs50.pop(0)
  for tr in trs50:
    ligne = []
    tds = tr.find_all("td")
    for td in tds:
      ligne.append(td.getText())
    dataset.append([discipline,"Femme","50"]+ligne)
  #Bassin de 25 mètres
  trs25 = tables[1].tbody.find_all("tr")
  trs25.pop(0)
  for tr in trs25:
    ligne = []
    tds = tr.find_all("td")
    for td in tds:
      ligne.append(td.getText())
    dataset.append([discipline,"Femme","25"]+ligne)

In [70]:
#100 dos et 200 dos

#Cas particulier du 100mdos où le tableau n'est pas le même:
time.sleep(0.8)
url = 'https://fr.wikipedia.org/wiki/Record_du_monde_de_natation_dames_du_100_m%C3%A8tres_dos'
response = requests.get(url, headers=headers)
soup = BeautifulSoup(response.content, 'lxml')
divs = soup.find_all("div", {"class":"mw-body-content mw-content-ltr"})
div = divs[0]
spans = div.find_all("span", {"class":"mw-headline"})
tables = div.find_all("table", {"class" : "wikitable sortable"})

#Bassin de 50 mètres
trs50 = tables[0].tbody.find_all("tr")
trs50.pop(0)
for tr in trs50:
  ligne = []
  tds = tr.find_all("td")
  for td in tds:
    ligne.append(td.getText())
  if len(ligne)==10:
    dataset.append(["100_mètres_dos","Femme","50", ligne[0], ligne[3], ligne[4], ligne[5],ligne[6],ligne[7],ligne[8],ligne[9]])
#Bassin de 25 mètres
trs25 = tables[1].tbody.find_all("tr")
trs25.pop(0)
for tr in trs25:
  ligne = []
  tds = tr.find_all("td")
  for td in tds:
    ligne.append(td.getText())
  dataset.append(["100_mètres_dos","Femme","25"]+ligne)

#Cas particulier du 200mdos où le tableau n'est pas le même:
time.sleep(0.8)
url = 'https://fr.wikipedia.org/wiki/Record_du_monde_de_natation_dames_du_200_m%C3%A8tres_dos'
response = requests.get(url, headers=headers)
soup = BeautifulSoup(response.content, 'lxml')
divs = soup.find_all("div", {"class":"mw-body-content mw-content-ltr"})
div = divs[0]
spans = div.find_all("span", {"class":"mw-headline"})
tables = div.find_all("table", {"class" : "wikitable sortable"})

#Bassin de 50 mètres
trs50 = tables[0].tbody.find_all("tr")
trs50.pop(0)
for tr in trs50:
  ligne = []
  tds = tr.find_all("td")
  for td in tds:
    ligne.append(td.getText())
  if len(ligne)==11:
    dataset.append(["200_mètres_dos","Femme","50", ligne[0], ligne[4], ligne[5],ligne[6],ligne[7],ligne[8],ligne[9],ligne[10]])
#Bassin de 25 mètres
trs25 = tables[1].tbody.find_all("tr")
trs25.pop(0)
for tr in trs25:
  ligne = []
  tds = tr.find_all("td")
  for td in tds:
    ligne.append(td.getText())
  dataset.append(["200_mètres_dos","Femme","25"]+ligne)

In [71]:
compt=0
for i in range(len(dataset)):
  if len(dataset[i])!=11:
    print(len(dataset[i]))
    print(dataset[i])
    compt+=1

print(compt)

4
['50_mètres_nage_libre', 'Femme', '50', 'Reconnaissance officielle du record par la FINA\n']
4
['100_mètres_nage_libre', 'Femme', '50', 'Nouvelles règles\n']
4
['200_mètres_nage_libre', 'Femme', '50', 'Nouvelles règles\n']
4
['400_mètres_nage_libre', 'Femme', '50', 'Nouvelles règles\n']
4
['50_mètres_papillon', 'Femme', '50', 'Record reconnu par la FINA\n']
4
['100_mètres_papillon', 'Femme', '50', 'Nouvelles règles\n']
4
['200_mètres_papillon', 'Femme', '50', 'Nouveau règlement\n']
4
['400_mètres_4_nages', 'Femme', '50', 'Nouvelles règles\n']
8

In [73]:
#On retire les lignes de non record (intrus du tableau)
for i in range (len(dataset)):
  if len(dataset[i])==4:
    dataset.pop(i)

In [74]:
print(dataset)

[['50_mètres_nage_libre', 'Femme', '50', '26 s 99\n', 'Kornelia Ender\n', '1958\n', '17\n', " Allemagne de l'Est\n", '\n', ' Cali\n', '26 juillet 1975\n'], ['50_mètres_nage_libre', 'Femme', '50', '26 s 95\n', 'Johanna Malloy\n', '1961\n', '16\n', ' Canada\n', '\n', " Saint John's\n", '16 août 1977\n'], ['50_mètres_nage_libre', 'Femme', '50', '26 s 74\n', 'Anne Jardin\n', '1959\n', '19\n', ' Canada\n', '\n', ' Etobicoke\n', '19 août 1978\n'], ['50_mètres_nage_libre', 'Femme', '50', '26 s 61\n', 'Cynthia Woodhead\n', '1964\n', '16\n', ' États-Unis\n', '\n', ' Austin\n', '10 avril 1980\n'], ['50_mètres_nage_libre', 'Femme', '50', '26 s 53\n', 'Kelly Asplund\n', '1961\n', '19\n', ' États-Unis\n', '\n', ' Austin\n', '10 avril 1980\n'], ['50_mètres_nage_libre', 'Femme', '50', '26 s 32\n', 'Jill Sterkel\n', '1961\n', '19\n', ' États-Unis\n', '\n', ' Austin\n', '10 avril 1980\n'], ['50_mètres_nage_libre', 'Femme', '50', '25 s 96\n', 'Jill Sterkel\n', '1961\n', '19\n', ' États-Unis\n', '\n', ' Austin\n', '10 avril 1980\n'], ['50_mètres_nage_libre', 'Femme', '50', '25 s 79\n', 'Jill Sterkel\n', '1961\n', '20\n', ' États-Unis\n', '\n', ' Austin\n', '3 avril 1981\n'], ['50_mètres_nage_libre', 'Femme', '50', '25 s 69\n', 'Dara Torres\n', '1967\n', '15\n', ' États-Unis\n', "Meeting d'Amersfoort\n", ' Amersfoort\n', '29 janvier 1982\n'], ['50_mètres_nage_libre', 'Femme', '50', '25 s 64\n', 'Anne Marie Verstappen\n', '1967\n', '16\n', ' Pays-Bas\n', 'Championnats des Pays-Bas\n', ' Amersfoort\n', '9 juillet 1983\n'], ['50_mètres_nage_libre', 'Femme', '50', '25 s 62\n', 'Dara Torres\n', '1967\n', '16\n', ' États-Unis\n', 'Championnats USA\n', ' Clovis\n', '5 août 1983\n'], ['50_mètres_nage_libre', 'Femme', '50', '25 s 61\n', 'Dara Torres\n', '1967\n', '17\n', ' États-Unis\n', 'Pré-Olympiques (r)[1]\n', ' Mission Viejo\n', '21 juillet 1984\n'], ['50_mètres_nage_libre', 'Femme', '50', '25 s 50\n', 'Tamara Costache\n', '1970\n', '16\n', ' Roumanie\n', 'Championnats de Roumanie\n', ' Bucarest\n', '14 juin 1986\n'], ['50_mètres_nage_libre', 'Femme', '50', '25 s 50\n', 'Tamara Costache\n', '1970\n', '16\n', ' Roumanie\n', 'Championnats de Roumanie\n', ' Bucarest\n', '14 juin 1986\n'], ['50_mètres_nage_libre', 'Femme', '50', '25 s 34\n', 'Tamara Costache\n', '1970\n', '16\n', ' Roumanie\n', 'Championnats de Roumanie (f)[2]\n', ' Bucarest\n', '16 juin 1986\n'], ['50_mètres_nage_libre', 'Femme', '50', '25 s 31\n', 'Tamara Costache\n', '1970\n', '16\n', ' Roumanie\n', 'Jeux balkaniques\n', ' Sofia\n', '1er août 1986\n'], ['50_mètres_nage_libre', 'Femme', '50', '25 s 28\n', 'Tamara Costache\n', '1970\n', '16\n', ' Roumanie\n', 'Championnats du Monde (f)\n', ' Madrid\n', '23 août 1986\n'], ['50_mètres_nage_libre', 'Femme', '50', '24 s 98\n', 'Wenji Yang\n', '1972\n', '16\n', ' Chine\n', 'Jeux asiatiques\n', ' Guangzhou\n', '11 avril 1988\n'], ['50_mètres_nage_libre', 'Femme', '50', '24 s 79\n', 'Wenji Yang\n', '1972\n', '20\n', ' Chine\n', 'Jeux olympiques (f)\n', ' Barcelone\n', '31 juillet 1992\n'], ['50_mètres_nage_libre', 'Femme', '50', '24 s 51\n', 'Jingyi Le\n', '1975\n', '19\n', ' Chine\n', 'Championnats du monde (f)\n', ' Rome\n', '11 septembre 1994\n'], ['50_mètres_nage_libre', 'Femme', '50', '24 s 51\n', 'Inge de Bruijn\n', '1973\n', '27\n', ' Pays-Bas\n', 'Super Speedo grand prix (s)\n', ' Sheffield\n', '27 mai 2000\n'], ['50_mètres_nage_libre', 'Femme', '50', '24 s 48\n', 'Inge de Bruijn\n', '1973\n', '27\n', ' Pays-Bas\n', 'Championnats des Pays-Bas\n', ' Amsterdam\n', '4 juin 2000\n'], ['50_mètres_nage_libre', 'Femme', '50', '24 s 39\n', 'Inge de Bruijn\n', '1973\n', '27\n', ' Pays-Bas\n', 'Championnats du Brésil\n', ' Rio de Janeiro\n', '10 juin 2000\n'], ['50_mètres_nage_libre', 'Femme', '50', '24 s 13\n', 'Inge de Bruijn\n', '1973\n', '27\n', ' Pays-Bas\n', 'Jeux olympiques (d)[3]\n', ' Sydney\n', '22 septembre 2000\n'], ['50_mètres_nage_libre', 'Femme', '50', '24 s 09\n', 'Marleen Veldhuis\n', '1979\n', '28\n', ' Pays-Bas\n', "Championnats d'Europe\n", ' Eindhoven\n', '24 mars 2008\n'], ['50_mètres_nage_libre', 'Femme', '50', '23 s 97\n', 'Libby Trickett\n', '1985\n', '23\n', ' Australie\n', "Championnats d'Australie (f)[2]\n", ' Sydney\n', '29 mars 2008\n'], ['50_mètres_nage_libre', 'Femme', '50', '23 s 96[4]\n', 'Marleen Veldhuis\n', '1979\n', '30\n', ' Pays-Bas\n', 'Amsterdam swim cup (f)\n', ' Amsterdam\n', '19 avril 2009\n'], ['50_mètres_nage_libre', 'Femme', '50', '23 s 73[5]\n', 'Britta Steffen\n', '1983\n', '25\n', ' Allemagne\n', 'Championnats du monde (f)\n', ' Rome\n', '2 août 2009\n'], ['50_mètres_nage_libre', 'Femme', '50', '23 s 67[6]\n', 'Sarah Sjöström\n', '1993\n', '23\n', ' Suède\n', 'Championnats du monde (d)\n', ' Budapest\n', '29 juillet 2017\n'], ['50_mètres_nage_libre', 'Femme', '25', '23 s 59[7]\n', 'Cate Campbell\n', '1992\n', '24\n', ' Australie\n', 'Australia grand prix[8]\n', ' Brisbane\n', '1er juillet 2016\n'], ['50_mètres_nage_libre', 'Femme', '25', '23 s 37[7]\n', 'Cate Campbell\n', '1992\n', '24\n', ' Australie\n', 'Australia grand prix[9]\n', ' Brisbane\n', '2 juillet 2016\n'], ['100_mètres_nage_libre', 'Femme', '50', '1 min 35 s 0\n', 'Martha Gerstung\n', '\n', '\n', ' Empire allemand\n', '\n', ' Magdebourg\n', '18 octobre 1908\n'], ['100_mètres_nage_libre', 'Femme', '50', '1 min 26 s 6\n', 'Claire Guttenstein\n', '1888\n', '22\n', ' Belgique\n', '\n', ' Schaerbeek\n', '2 octobre 1910\n'], ['100_mètres_nage_libre', 'Femme', '50', '1 min 24 s 6\n', 'Daisy Curwen\n', '\n', '\n', ' Royaume-Uni\n', '\n', ' Liverpool\n', '29 juillet 1911\n'], ['100_mètres_nage_libre', 'Femme', '50', '1 min 20 s 6\n', 'Daisy Curwen\n', '\n', '\n', ' Royaume-Uni\n', '\n', ' Birkenhead\n', '10 juin 1912\n'], ['100_mètres_nage_libre', 'Femme', '50', '1 min 19 s 8\n', 'Fanny Durack\n', '1889\n', '23\n', ' Australie\n', '\n', ' Stockholm\n', '9 juillet 1912\n'], ['100_mètres_nage_libre', 'Femme', '50', '1 min 18 s 8\n', 'Fanny Durack\n', '1889\n', '23\n', ' Australie\n', '\n', ' Hambourg\n', '21 juillet 1912\n'], ['100_mètres_nage_libre', 'Femme', '50', '1 min 16 s 2\n', 'Fanny Durack\n', '1889\n', '26\n', ' Australie\n', '\n', ' Sydney\n', '6 février 1915\n'], ['100_mètres_nage_libre', 'Femme', '50', '1 min 13 s 6\n', 'Ethelda Bleibtrey\n', '1902\n', '18\n', ' États-Unis\n', 'Jeux olympiques\n', ' Anvers\n', '25 août 1920\n'], ['100_mètres_nage_libre', 'Femme', '50', '1 min 12 s 8\n', 'Gertrude Ederle\n', '1906\n', '17\n', ' États-Unis\n', '\n', ' Newark\n', '30 juin 1923\n'], ['100_mètres_nage_libre', 'Femme', '50', '1 min 12 s 2\n', 'Mariechen Wehselau\n', '\n', '\n', ' États-Unis\n', '\n', ' Paris\n', '19 juillet 1924\n'], ['100_mètres_nage_libre', 'Femme', '50', '1 min 10 s 0\n', 'Ethel Lackie\n', '\n', '\n', ' États-Unis\n', '\n', ' Toledo\n', '28 janvier 1926\n'], ['100_mètres_nage_libre', 'Femme', '50', '1 min 09 s 8\n', 'Eleanor Garatti\n', '1909\n', '20\n', ' États-Unis\n', '\n', ' Honolulu\n', '7 août 1929\n'], ['100_mètres_nage_libre', 'Femme', '50', '1 min 09 s 4\n', 'Albina Osipowich\n', '\n', '\n', ' États-Unis\n', '\n', ' San Francisco\n', '25 août 1929\n'], ['100_mètres_nage_libre', 'Femme', '50', '1 min 08 s 0\n', 'Helene Madison\n', '1913\n', '17\n', ' États-Unis\n', '\n', ' Miami Beach\n', '14 mars 1930\n'], ['100_mètres_nage_libre', 'Femme', '50', '1 min 06 s 6\n', 'Helene Madison\n', '1913\n', '18\n', ' États-Unis\n', '\n', ' Boston\n', '20 avril 1931\n'], ['100_mètres_nage_libre', 'Femme', '50', '1 min 06 s 0\n', 'Willy den Ouden\n', '1918\n', '15\n', ' Pays-Bas\n', '\n', ' Anvers\n', '9 juillet 1933\n'], ['100_mètres_nage_libre', 'Femme', '50', '1 min 05 s 4\n', 'Willy den Ouden\n', '1918\n', '17\n', ' Pays-Bas\n', '\n', ' Amsterdam\n', '24 février 1934\n'], ['100_mètres_nage_libre', 'Femme', '50', '1 min 04 s 8\n', 'Willy den Ouden\n', '1918\n', '17\n', ' Pays-Bas\n', '\n', ' Rotterdam\n', '15 avril 1934\n'], ['100_mètres_nage_libre', 'Femme', '50', '1 min 04 s 6\n', 'Willy den Ouden\n', '1918\n', '18\n', ' Pays-Bas\n', '\n', ' Amsterdam\n', '27 février 1936\n'], ['100_mètres_nage_libre', 'Femme', '50', '1 min 04 s 5\n', 'Dawn Fraser\n', '1937\n', '19\n', ' Australie\n', '\n', ' Sydney\n', '21 février 1956\n'], ['100_mètres_nage_libre', 'Femme', '50', '1 min 04 s 2\n', 'Cockie Gastelaars\n', '\n', '\n', ' Pays-Bas\n', '\n', ' Amsterdam\n', '3 mars 1956\n'], ['100_mètres_nage_libre', 'Femme', '50', '1 min 04 s 0\n', 'Cockie Gastelaars\n', '\n', '\n', ' Pays-Bas\n', '\n', ' Schiedam\n', '14 avril 1956\n'], ['100_mètres_nage_libre', 'Femme', '50', '1 min 03 s 3\n', 'Dawn Fraser\n', '1937\n', '19\n', ' Australie\n', '\n', ' Townsville\n', '25 août 1956\n'], ['100_mètres_nage_libre', 'Femme', '50', '1 min 03 s 2\n', 'Lorraine Crapp\n', '1938\n', '18\n', ' Australie\n', '\n', ' Sydney\n', '25 octobre 1956\n'], ['100_mètres_nage_libre', 'Femme', '50', '1 min 02 s 4\n', 'Lorraine Crapp\n', '1938\n', '18\n', ' Australie\n', '\n', ' Melbourne\n', '1er décembre 1956\n'], ['100_mètres_nage_libre', 'Femme', '50', '1 min 02 s 0\n', 'Dawn Fraser\n', '1937\n', '19\n', ' Australie\n', '\n', ' Melbourne\n', '1er décembre 1956\n'], ['100_mètres_nage_libre', 'Femme', '50', '1 min 01 s 5 (y)[1]\n', 'Dawn Fraser\n', '1937\n', '21\n', ' Australie\n', '\n', ' Melbourne\n', '18 février 1958\n'], ['100_mètres_nage_libre', 'Femme', '50', '1 min 01 s 4 (y)\n', 'Dawn Fraser\n', '1937\n', '21\n', ' Australie\n', '\n', ' Cardiff\n', '21 juillet 1958\n'], ['100_mètres_nage_libre', 'Femme', '50', '1 min 01 s 2\n', 'Dawn Fraser\n', '1937\n', '21\n', ' Australie\n', '\n', ' Schiedam\n', '10 août 1958\n'], ['100_mètres_nage_libre', 'Femme', '50', '1 min 00 s 2 (y)\n', 'Dawn Fraser\n', '1937\n', '23\n', ' Australie\n', '\n', ' Sydney\n', '23 février 1960\n'], ['100_mètres_nage_libre', 'Femme', '50', '1 min 00 s 0 (y)\n', 'Dawn Fraser\n', '1937\n', '25\n', ' Australie\n', '\n', ' Melbourne\n', '23 octobre 1962\n'], ['100_mètres_nage_libre', 'Femme', '50', '59 s 9 (y)\n', 'Dawn Fraser\n', '1937\n', '25\n', ' Australie\n', '\n', ' Melbourne\n', '27 octobre 1962\n'], ['100_mètres_nage_libre', 'Femme', '50', '59 s 5 (y)\n', 'Dawn Fraser\n', '1937\n', '25\n', ' Australie\n', '\n', ' Perth\n', '24 novembre 1962\n'], ['100_mètres_nage_libre', 'Femme', '50', '58 s 9\n', 'Dawn Fraser\n', '1937\n', '27\n', ' Australie\n', '\n', ' Sydney\n', '29 février 1964\n'], ['100_mètres_nage_libre', 'Femme', '50', '58 s 9\n', 'Shane Gould\n', '1956\n', '15\n', ' Australie\n', '\n', ' Londres\n', '30 avril 1971\n'], ['100_mètres_nage_libre', 'Femme', '50', '58 s 5\n', 'Shane Gould\n', '1956\n', '16\n', ' Australie\n', '\n', ' Sydney\n', '8 janvier 1972\n'], ['100_mètres_nage_libre', 'Femme', '50', '58 s 25\n', 'Kornelia Ender\n', '1958\n', '15\n', " Allemagne de l'Est\n", '\n', ' Berlin\n', '13 juillet 1973\n'], ['100_mètres_nage_libre', 'Femme', '50', '58 s 12\n', 'Kornelia Ender\n', '1958\n', '15\n', " Allemagne de l'Est\n", '\n', ' Utrecht\n', '18 août 1973\n'], ['100_mètres_nage_libre', 'Femme', '50', '57 s 61\n', 'Kornelia Ender\n', '1958\n', '15\n', " Allemagne de l'Est\n", 'Championnats du monde\n', ' Belgrade\n', '8 septembre 1973\n'], ['100_mètres_nage_libre', 'Femme', '50', '57 s 54\n', 'Kornelia Ender\n', '1958\n', '15\n', " Allemagne de l'Est\n", 'Championnats du monde\n', ' Belgrade\n', '9 septembre 1973\n'], ['100_mètres_nage_libre', 'Femme', '50', '57 s 51\n', 'Kornelia Ender\n', '1958\n', '16\n', " Allemagne de l'Est\n", '\n', ' Rostock\n', '4 juillet 1974\n'], ['100_mètres_nage_libre', 'Femme', '50', '56 s 96\n', 'Kornelia Ender\n', '1958\n', '16\n', " Allemagne de l'Est\n", "Championnats d'Europe\n", ' Vienne\n', '19 août 1974\n'], ['100_mètres_nage_libre', 'Femme', '50', '56 s 38\n', 'Kornelia Ender\n', '1958\n', '17\n', " Allemagne de l'Est\n", '\n', ' Dresde\n', '14 mars 1975\n'], ['100_mètres_nage_libre', 'Femme', '50', '56 s 22\n', 'Kornelia Ender\n', '1958\n', '17\n', " Allemagne de l'Est\n", 'Championnats du monde\n', ' Cali\n', '26 juillet 1975\n'], ['100_mètres_nage_libre', 'Femme', '50', '55 s 73\n', 'Kornelia Ender\n', '1958\n', '18\n', " Allemagne de l'Est\n", '\n', ' Berlin\n', '6 juin 1976\n'], ['100_mètres_nage_libre', 'Femme', '50', '55 s 65\n', 'Kornelia Ender\n', '1958\n', '18\n', " Allemagne de l'Est\n", 'Jeux olympiques\n', ' Montréal\n', '19 juillet 1976\n'], ['100_mètres_nage_libre', 'Femme', '50', '55 s 41\n', 'Barbara Krause\n', '1959\n', '19\n', " Allemagne de l'Est\n", "Championnats d'Allemagne de l'Est\n", ' Berlin\n', '5 juillet 1978\n'], ['100_mètres_nage_libre', 'Femme', '50', '54 s 98\n', 'Barbara Krause\n', '1959\n', '21\n', " Allemagne de l'Est\n", 'Jeux olympiques (s)[2]\n', ' Moscou\n', '20 juillet 1980\n'], ['100_mètres_nage_libre', 'Femme', '50', '54 s 79\n', 'Barbara Krause\n', '1959\n', '21\n', " Allemagne de l'Est\n", 'Jeux olympiques (f)[3]\n', ' Moscou\n', '21 juillet 1980\n'], ['100_mètres_nage_libre', 'Femme', '50', '54 s 73\n', 'Kristin Otto\n', '1966\n', '20\n', " Allemagne de l'Est\n", 'Championnats du monde\n', ' Madrid\n', '19 août 1986\n'], ['100_mètres_nage_libre', 'Femme', '50', '54 s 48\n', 'Jenny Thompson\n', '1973\n', '19\n', ' États-Unis\n', 'Championnats USA (s)\n', ' Indianapolis\n', '1er mars 1992\n'], ['100_mètres_nage_libre', 'Femme', '50', '54 s 01\n', 'Jingyi Le\n', '1975\n', '19\n', ' Chine\n', 'Championnats du monde (f)\n', ' Rome\n', '5 septembre 1994\n'], ['100_mètres_nage_libre', 'Femme', '50', '53 s 80\n', 'Inge de Bruijn\n', '1973\n', '27\n', ' Pays-Bas\n', 'Speedo Grand Prix meet\n', ' Sheffield\n', '28 mai 2000\n'], ['100_mètres_nage_libre', 'Femme', '50', '53 s 77\n', 'Inge de Bruijn\n', '1973\n', '27\n', ' Pays-Bas\n', 'Jeux olympiques (d)[4]\n', ' Sydney\n', '20 septembre 2000\n'], ['100_mètres_nage_libre', 'Femme', '50', '53 s 66\n', 'Lisbeth Lenton\n', '1985\n', '19\n', ' Australie\n', "Championnats d'Australie (d)\n", ' Sydney\n', '31 mars 2004\n'], ['100_mètres_nage_libre', 'Femme', '50', '53 s 52\n', 'Jodie Henry\n', '1983\n', '21\n', ' Australie\n', 'Jeux olympiques (d)\n', ' Athènes\n', '18 août 2004\n'], ['100_mètres_nage_libre', 'Femme', '50', '53 s 42\n', 'Lisbeth Lenton\n', '1985\n', '21\n', ' Australie\n', 'Sélections des jeux du Commonwealth (d)\n', ' Melbourne\n', '31 janvier 2006\n'], ['100_mètres_nage_libre', 'Femme', '50', '53 s 30\n', 'Britta Steffen\n', '1983\n', '23\n', ' Allemagne\n', "Championnats d'Europe (f)\n", ' Budapest\n', '2 août 2006\n'], ['100_mètres_nage_libre', 'Femme', '50', '52 s 99[5]\n', 'Lisbeth Lenton\n', '1985\n', '22\n', ' Australie\n', 'Duel in the Pool (r)[6]\n', ' Sydney\n', '3 avril 2007\n'], ['100_mètres_nage_libre', 'Femme', '50', '52 s 88\n', 'Lisbeth Trickett-Lenton\n', '1985\n', '23\n', ' Australie\n', "Championnats d'Australie de natation (f)\n", ' Sydney\n', '27 mars 2008\n'], ['100_mètres_nage_libre', 'Femme', '50', '52 s 85[7]\n', 'Britta Steffen\n', '1983\n', '26\n', ' Allemagne\n', "Championnat d'Allemagne (s)\n", ' Berlin\n', '25 juin 2009\n'], ['100_mètres_nage_libre', 'Femme', '50', '52 s 56[8]\n', 'Britta Steffen\n', '1983\n', '26\n', ' Allemagne\n', "Championnat d'Allemagne (f)\n", ' Berlin\n', '27 juin 2009\n'], ['100_mètres_nage_libre', 'Femme', '50', '52 s 22[9]\n', 'Britta Steffen\n', '1983\n', '26\n', ' Allemagne\n', 'Championnats du monde (rf)\n', ' Rome\n', '26 juillet 2009\n'], ['100_mètres_nage_libre', 'Femme', '50', '52 s 07[10]\n', 'Britta Steffen\n', '1983\n', '26\n', ' Allemagne\n', 'Championnats du monde (f)\n', ' Rome\n', '31 juillet 2009\n'], ['100_mètres_nage_libre', 'Femme', '50', '52 s 06[11]\n', 'Cate Campbell\n', '1992\n', '24\n', ' Australie\n', 'Australia grand prix\n', ' Brisbane\n', '2 juillet 2016\n'], ['100_mètres_nage_libre', 'Femme', '50', '51 s 71\n', 'Sarah Sjöström\n', '1993\n', '23\n', ' Suède\n', 'Championnats du monde (rf)\n', ' Budapest\n', '23 juillet 2017\n'], ['100_mètres_nage_libre', 'Femme', '25', '51 s 59[12]\n', 'Cate Campbell\n', '1992\n', '22\n', ' Australie\n', 'Jeux du Commonwealth (rf[13])\n', ' Glasgow\n', '29 juillet 2014\n'], ['100_mètres_nage_libre', 'Femme', '25', '52 s 70[14]\n', 'Penny Oleksiak\n', '2000\n', '16\n', ' Canada\n', 'Jeux olympiques (Record olympique)\n', ' Rio de Janeiro\n', '11 août 2016\n'], ['200_mètres_nage_libre', 'Femme', '50', '2 min 56 s 0\n', 'Fanny Durack\n', '1889\n', '16\n', ' États-Unis\n', '\n', ' Manly\n', '4 mars 1905\n'], ['200_mètres_nage_libre', 'Femme', '50', '2 min 47 s 6\n', 'Charlotte Boyle\n', '\n', '\n', ' États-Unis\n', '\n', ' New Brighton\n', '25 août 1921\n'], ['200_mètres_nage_libre', 'Femme', '50', '2 min 45 s 2\n', 'Gertrude Ederle\n', '1905\n', '18\n', ' États-Unis\n', '\n', ' Brooklyn\n', '4 avril 1923\n'], ['200_mètres_nage_libre', 'Femme', '50', '2 min 40 s 6 (y)[1]\n', 'Martha Norelius\n', '1910\n', '16\n', ' États-Unis\n', '\n', ' Miami\n', '28 février 1926\n'], ['200_mètres_nage_libre', 'Femme', '50', '2 min 34 s 6\n', 'Helene Madison\n', '1913\n', '17\n', ' États-Unis\n', '\n', ' St. Augustine\n', '6 mars 1930\n'], ['200_mètres_nage_libre', 'Femme', '50', '2 min 28 s 6\n', 'Willy den Ouden\n', '1918\n', '15\n', ' Pays-Bas\n', '\n', ' Rotterdam\n', '3 mai 1933\n'], ['200_mètres_nage_libre', 'Femme', '50', '2 min 27 s 6 (y)\n', 'Willy den Ouden\n', '1918\n', '16\n', ' Pays-Bas\n', '\n', ' Durdee\n', '5 mai 1934\n'], ['200_mètres_nage_libre', 'Femme', '50', '2 min 25 s 3\n', 'Willy den Ouden\n', '1918\n', '17\n', ' Pays-Bas\n', '\n', ' Copenhague\n', '8 septembre 1935\n'], ['200_mètres_nage_libre', 'Femme', '50', '2 min 24 s 6\n', 'Rie Van Deen\n', '\n', '\n', ' Pays-Bas\n', '\n', ' Rotterdam\n', '26 février 1938\n'], ['200_mètres_nage_libre', 'Femme', '50', '2 min 21 s 7\n', 'Ragnhild Hveger\n', '1920\n', '18\n', ' Danemark\n', '\n', ' Aarhus\n', '11 septembre 1938\n'], ['200_mètres_nage_libre', 'Femme', '50', '2 min 20 s 7\n', 'Dawn Fraser\n', '1937\n', '19\n', ' Australie\n', '\n', ' Sydney\n', '25 février 1956\n'], ['200_mètres_nage_libre', 'Femme', '50', '2 min 19 s 3\n', 'Lorraine Crapp\n', '1938\n', '18\n', ' Australie\n', '\n', ' Townsville\n', '25 août 1956\n'], ['200_mètres_nage_libre', 'Femme', '50', '2 min 18 s 5\n', 'Lorraine Crapp\n', '1938\n', '18\n', ' Australie\n', '\n', ' Sydney\n', '20 octobre 1956\n'], ['200_mètres_nage_libre', 'Femme', '50', '2 min 17 s 7 (y)\n', 'Dawn Fraser\n', '1937\n', '21\n', ' Australie\n', '\n', ' Adélaïde\n', '10 février 1958\n'], ['200_mètres_nage_libre', 'Femme', '50', '2 min 14 s 7 (y)\n', 'Dawn Fraser\n', '1937\n', '21\n', ' Australie\n', '\n', ' Melbourne\n', '22 février 1958\n'], ['200_mètres_nage_libre', 'Femme', '50', '2 min 11 s 6 (y)\n', 'Dawn Fraser\n', '1937\n', '23\n', ' Australie\n', '\n', ' Sydney\n', '27 février 1960\n'], ['200_mètres_nage_libre', 'Femme', '50', '2 min 10 s 5\n', 'Pokey Watson\n', '\n', '\n', ' États-Unis\n', '\n', ' Lincoln\n', '19 août 1966\n'], ['200_mètres_nage_libre', 'Femme', '50', '2 min 09 s 7\n', 'Pam Kruse\n', '\n', '\n', ' États-Unis\n', '\n', ' Philadelphie\n', '19 août 1967\n'], ['200_mètres_nage_libre', 'Femme', '50', '2 min 09 s 5\n', 'Sue Pedersen\n', '\n', '\n', ' États-Unis\n', '\n', ' Santa Clara\n', '6 juillet 1968\n'], ['200_mètres_nage_libre', 'Femme', '50', '2 min 08 s 8\n', 'Edith Wetzel\n', '\n', '\n', ' États-Unis\n', '\n', ' Lincoln\n', '2 août 1968\n'], ['200_mètres_nage_libre', 'Femme', '50', '2 min 06 s 7\n', 'Debbie Meyer\n', '1952\n', '16\n', ' États-Unis\n', '\n', ' Los Angeles\n', '24 août 1968\n'], ['200_mètres_nage_libre', 'Femme', '50', '2 min 06 s 5\n', 'Shane Gould\n', '1956\n', '15\n', ' Australie\n', '\n', ' Londres\n', '1er mai 1971\n'], ['200_mètres_nage_libre', 'Femme', '50', '2 min 05 s 8\n', 'Shane Gould\n', '1956\n', '15\n', ' Australie\n', '\n', ' Sydney\n', '26 novembre 1971\n'], ['200_mètres_nage_libre', 'Femme', '50', '2 min 05 s 21\n', 'Shirley Babashoff\n', '1957\n', '15\n', ' États-Unis\n', '\n', ' Chicago\n', '4 août 1972\n'], ['200_mètres_nage_libre', 'Femme', '50', '2 min 03 s 56\n', 'Shane Gould\n', '1956\n', '16\n', ' Australie\n', 'Jeux olympiques\n', ' Munich\

In [75]:
#Mise en forme de l'age, la nationalité, la competition, le lieu et la date :
for row in dataset:
  if row[6]!= None:
    row[6] = row[6].split('\n')[0]
  row[7] = row[7].split('\n')[0]
  row[8] = row[8].split('\n')[0]
  row[9] = row[9].split('\n')[0]
  row[10] = row[10].split('\n')[0]

In [ ]:
#Mise en forme de la date I/II
for row in dataset:
  date_prov = row[10].split(" ")
  try:
    if date_prov[1] == 'janvier':
        row[10] = date_prov[2]+'-'+'01'+'-'+ date_prov[0]
    if date_prov[1] == 'février':
        row[10] = date_prov[2]+'-'+'02'+'-'+ date_prov[0]
    if date_prov[1] == 'mars':
        row[10] = date_prov[2]+'-'+'03'+'-'+ date_prov[0]
    if date_prov[1] == 'avril':
        row[10] = date_prov[2]+'-'+'04'+'-'+ date_prov[0]
    if date_prov[1] == 'mai':
        row[10] = date_prov[2]+'-'+'05'+'-'+ date_prov[0]
    if date_prov[1] == 'juin':
        row[10] = date_prov[2]+'-'+'06'+'-'+ date_prov[0]
    if date_prov[1] == 'juillet':
        row[10] = date_prov[2]+'-'+'07'+'-'+ date_prov[0]
    if date_prov[1] == 'août':
        row[10] = date_prov[2]+'-'+'08'+'-'+ date_prov[0]
    if date_prov[1] == 'septembre':
        row[10] = date_prov[2]+'-'+'09'+'-'+ date_prov[0]
    if date_prov[1] == 'octobre':
        row[10] = date_prov[2]+'-'+'10'+'-'+ date_prov[0]
    if date_prov[1] == 'novembre':
        row[10] = date_prov[2]+'-'+'11'+'-'+ date_prov[0]
    if date_prov[1] == 'décembre':
        row[10] = date_prov[2]+'-'+'12'+'-'+ date_prov[0]
  except:
    print(row)

#Mise en forme de la date II/II
for row in dataset:
  if 'février' in row[-1]:
    row[-1]=row[-1].split('février ')[1]
    
  if '1er' in row[-1]:
    row[-1]=row[-1].split('1er')[0]+ '1'

for row in dataset:
  if '1er' in row[-1]:
    row[-1]=row[-1].split('1er')[0]+ '1'

In [77]:
#Mise en forme du temps
for row in dataset:
  if len(row[3].split('\n'))!=2:
    row[3]=row[3].split('\n')[1]+'\n'

for row in dataset:
  row[3]= row[3].split('\n')[0]

for row in dataset:
  if len(row[3].split('['))!=1:
    row[3]=row[3].split('[')[0]

for row in dataset:
  row[3]=row[3].split('(')[0]

for row in dataset:
  if len(row[3].split('min'))==2:
    row[3]=row[3].split(' min ')[0]+':'+row[3].split(' min ')[1]
  
  if len(row[3].split(' s '))==2:
    row[3]=row[3].split(' s ')[0]+':'+row[3].split(' s ')[1]

In [79]:
for i in range(len(dataset)):
  if '---' in dataset[i][3]:
    dataset.pop(i)
  if len(dataset[i][3])==0:
    dataset.pop(i)

In [80]:
pd.set_option('display.max_rows', None)
df = pd.DataFrame(dataset, columns = ["Discipline", "Sexe", "Bassin (m)","Temps", "Nom", "Naissance", "Age", "Nationalite", "Competition", "Lieu", "Date"])
del df["Competition"]
del df["Nom"]
del df["Naissance"]
df

                 Discipline   Sexe  ...                       Lieu            Date
0      50_mètres_nage_libre  Femme  ...                       Cali      1975-07-26
1      50_mètres_nage_libre  Femme  ...               Saint John's      1977-08-16
2      50_mètres_nage_libre  Femme  ...                  Etobicoke      1978-08-19
3      50_mètres_nage_libre  Femme  ...                     Austin      1980-04-10
4      50_mètres_nage_libre  Femme  ...                     Austin      1980-04-10
5      50_mètres_nage_libre  Femme  ...                     Austin      1980-04-10
6      50_mètres_nage_libre  Femme  ...                     Austin      1980-04-10
7      50_mètres_nage_libre  Femme  ...                     Austin       1981-04-3
8      50_mètres_nage_libre  Femme  ...                 Amersfoort      1982-01-29
9      50_mètres_nage_libre  Femme  ...                 Amersfoort       1983-07-9
10     50_mètres_nage_libre  Femme  ...                     Clovis       1983-08-5
11     50_mètres_nage_libre  Femme  ...              Mission Viejo      1984-07-21
12     50_mètres_nage_libre  Femme  ...                   Bucarest      1986-06-14
13     50_mètres_nage_libre  Femme  ...                   Bucarest      1986-06-14
14     50_mètres_nage_libre  Femme  ...                   Bucarest      1986-06-16
15     50_mètres_nage_libre  Femme  ...                      Sofia       1986-08-1
16     50_mètres_nage_libre  Femme  ...                     Madrid      1986-08-23
17     50_mètres_nage_libre  Femme  ...                  Guangzhou      1988-04-11
18     50_mètres_nage_libre  Femme  ...                  Barcelone      1992-07-31
19     50_mètres_nage_libre  Femme  ...                       Rome      1994-09-11
20     50_mètres_nage_libre  Femme  ...                  Sheffield      2000-05-27
21     50_mètres_nage_libre  Femme  ...                  Amsterdam       2000-06-4
22     50_mètres_nage_libre  Femme  ...             Rio de Janeiro      2000-06-10
23     50_mètres_nage_libre  Femme  ...                     Sydney      2000-09-22
24     50_mètres_nage_libre  Femme  ...                  Eindhoven      2008-03-24
25     50_mètres_nage_libre  Femme  ...                     Sydney      2008-03-29
26     50_mètres_nage_libre  Femme  ...                  Amsterdam      2009-04-19
27     50_mètres_nage_libre  Femme  ...                       Rome       2009-08-2
28     50_mètres_nage_libre  Femme  ...                   Budapest      2017-07-29
29     50_mètres_nage_libre  Femme  ...                   Brisbane       2016-07-1
30     50_mètres_nage_libre  Femme  ...                   Brisbane       2016-07-2
31    100_mètres_nage_libre  Femme  ...                 Magdebourg      1908-10-18
32    100_mètres_nage_libre  Femme  ...                 Schaerbeek       1910-10-2
33    100_mètres_nage_libre  Femme  ...                  Liverpool      1911-07-29
34    100_mètres_nage_libre  Femme  ...                 Birkenhead      1912-06-10
35    100_mètres_nage_libre  Femme  ...                  Stockholm       1912-07-9
36    100_mètres_nage_libre  Femme  ...                   Hambourg      1912-07-21
37    100_mètres_nage_libre  Femme  ...                     Sydney       1915-02-6
38    100_mètres_nage_libre  Femme  ...                     Anvers      1920-08-25
39    100_mètres_nage_libre  Femme  ...                     Newark      1923-06-30
40    100_mètres_nage_libre  Femme  ...                      Paris      1924-07-19
41    100_mètres_nage_libre  Femme  ...                     Toledo      1926-01-28
42    100_mètres_nage_libre  Femme  ...                   Honolulu       1929-08-7
43    100_mètres_nage_libre  Femme  ...              San Francisco      1929-08-25
44    100_mètres_nage_libre  Femme  ...                Miami Beach      1930-03-14
45    100_mètres_nage_libre  Femme  ...                     Boston      1931-04-20
46    100_mètres_nage_libre  Femme  ...                     Anvers       1933-07-9
47    100_mètres_nage_libre  Femme  ...                  Amsterdam      1934-02-24
48    100_mètres_nage_libre  Femme  ...                  Rotterdam      1934-04-15
49    100_mètres_nage_libre  Femme  ...                  Amsterdam      1936-02-27
50    100_mètres_nage_libre  Femme  ...                     Sydney      1956-02-21
51    100_mètres_nage_libre  Femme  ...                  Amsterdam       1956-03-3
52    100_mètres_nage_libre  Femme  ...                   Schiedam      1956-04-14
53    100_mètres_nage_libre  Femme  ...                 Townsville      1956-08-25
54    100_mètres_nage_libre  Femme  ...                     Sydney      1956-10-25
55    100_mètres_nage_libre  Femme  ...                  Melbourne       1956-12-1
56    100_mètres_nage_libre  Femme  ...                  Melbourne       1956-12-1
57    100_mètres_nage_libre  Femme  ...                  Melbourne      1958-02-18
58    100_mètres_nage_libre  Femme  ...                    Cardiff      1958-07-21
59    100_mètres_nage_libre  Femme  ...                   Schiedam      1958-08-10
60    100_mètres_nage_libre  Femme  ...                     Sydney      1960-02-23
61    100_mètres_nage_libre  Femme  ...                  Melbourne      1962-10-23
62    100_mètres_nage_libre  Femme  ...                  Melbourne      1962-10-27
63    100_mètres_nage_libre  Femme  ...                      Perth      1962-11-24
64    100_mètres_nage_libre  Femme  ...                     Sydney      1964-02-29
65    100_mètres_nage_libre  Femme  ...                    Londres      1971-04-30
66    100_mètres_nage_libre  Femme  ...                     Sydney       1972-01-8
67    100_mètres_nage_libre  Femme  ...                     Berlin      1973-07-13
68    100_mètres_nage_libre  Femme  ...                    Utrecht      1973-08-18
69    100_mètres_nage_libre  Femme  ...                   Belgrade       1973-09-8
70    100_mètres_nage_libre  Femme  ...                   Belgrade       1973-09-9
71    100_mètres_nage_libre  Femme  ...                    Rostock       1974-07-4
72    100_mètres_nage_libre  Femme  ...                     Vienne      1974-08-19
73    100_mètres_nage_libre  Femme  ...                     Dresde      1975-03-14
74    100_mètres_nage_libre  Femme  ...                       Cali      1975-07-26
75    100_mètres_nage_libre  Femme  ...                     Berlin       1976-06-6
76    100_mètres_nage_libre  Femme  ...                   Montréal      1976-07-19
77    100_mètres_nage_libre  Femme  ...                     Berlin       1978-07-5
78    100_mètres_nage_libre  Femme  ...                     Moscou      1980-07-20
79    100_mètres_nage_libre  Femme  ...                     Moscou      1980-07-21
80    100_mètres_nage_libre  Femme  ...                     Madrid      1986-08-19
81    100_mètres_nage_libre  Femme  ...               Indianapolis       1992-03-1
82    100_mètres_nage_libre  Femme  ...                       Rome       1994-09-5
83    100_mètres_nage_libre  Femme  ...                  Sheffield      2000-05-28
84    100_mètres_nage_libre  Femme  ...                     Sydney      2000-09-20
85    100_mètres_nage_libre  Femme  ...                     Sydney      2004-03-31
86    100_mètres_nage_libre  Femme  ...                    Athènes      2004-08-18
87    100_mètres_nage_libre  Femme  ...                  Melbourne      2006-01-31
88    100_mètres_nage_libre  Femme  ...                   Budapest       2006-08-2
89    100_mètres_nage_libre  Femme  ...                     Sydney       2007-04-3
90    100_mètres_nage_libre  Femme  ...                     Sydney      2008-03-27
91    100_mètres_nage_libre  Femme  ...                     Berlin      2009-06-25
92    100_mètres_nage_libre  Femme  ...                     Berlin      2009-06-27
93    100_mètres_nage_libre  Femme  ...                       Rome      2009-07-26
94    100_mètres_nage_libre  Femme  ...                       Rome      2009-07-31
95    100_mètres_nage_libre  Femme  ...                   Brisbane       2016-07-2
96    100_mètres_nage_libre  Femme  ...                   Budapest      2017-07-23
97    100_mètres_nage_libre  Femme  ...                    Glasgow      2014-07-29
98    100_mètres_nage_libre  Femme  ...             Rio de Janeiro      2016-08-11
99    200_mètres_nage_libre  Femme  ...                      Manly       1905-03-4
100   200_mètres_nage_libre  Femme  ...               New Brighton      1921-08-25
101   200_mètres_nage_libre  Femme  ...                   Brooklyn       1923-04-4
102   200_mètres_nage_libre  Femme  ...                      Miami      1926-02-28
103   200_mètres_nage_libre  Femme  ...              St. Augustine       1930-03-6
104   200_mètres_nage_libre  Femme  ...                  Rotterdam       1933-05-3
105   200_mètres_nage_libre  Femme  ...                     Durdee       1934-05-5
106   200_mètres_nage_libre  Femme  ...                 Copenhague       1935-09-8
107   200_mètres_nage_libre  Femme  ...                  Rotterdam      1938-02-26
108   200_mètres_nage_libre  Femme  ...                     Aarhus      1938-09-11
109   200_mètres_nage_libre  Femme  ...                     Sydney      1956-02-25
110   200_mètres_nage_libre  Femme  ...                 Townsville      1956-08-25
111   200_mètres_nage_libre  Femme  ...                     Sydney      1956-10-20
112   200_mètres_nage_libre  Femme  ...                   Adélaïde      1958-02-10
113   200_mètres_nage_libre  Femme  ...                  Melbourne      1958-02-22
114   200_mètres_nage_libre  Femme  ...                     Sydney      1960-02-27
115   200_mètres_nage_libre  Femme  ...                    Lincoln      1966-08-19
116   200_mètres_nage_libre  Femme  ...               Philadelphie      1967-08-19
117   200_mètres_nage_libre  Femme  ...                Santa Clara       1968-07-6
118   200_mètres_nage_libre  Femme  ...                    Lincoln       1968-08-2
119   200_mètres_nage_libre  Femme  ...                Los Angeles      1968-08-24
120   200_mètres_nage_libre  Femme  ...                    Londres       1971-05-1
121   200_mètres_nage_libre  Femme  ...                     Sydney      1971-11-26
122   200_mètres_nage_libre  Femme  ...                    Chicago       1972-08-4
123   200_mètres_nage_libre  Femme  ...                     Munich       1972-09-1
124   200_mètres_nage_libre  Femme  ...                     Vienne      1974-08-22
125   200_mètres_nage_libre  Femme  ...                    Concord      1974-08-23
126   200_mètres_nage_libre  Femme  ...                    Concord      1974-08-31
127   200_mètres_nage_libre  Femme  ...                     Dresde      1975-03-15
128   200_mètres_nage_libre  Femme  ...                     Berlin       1976-06-2
129   200_mètres_nage_libre  Femme  ...                   Montréal      1976-07-22
130   200_mètres_nage_libre  Femme  ...                 Berlin-Est       1978-07-2
131   200_mètres_nage_libre  Femme  ...               Berlin Ouest      1978-08-22
132   200_mètres_nage_libre  Femme  ...                   San Juan       1979-07-3
133   200_mètres_nage_libre  Femme  ...                      Tokyo       1979-09-3
134   200_mètres_nage_libre  Femme  ...                 Magdebourg      1984-05-23
135   200_mètres_nage_libre  Femme  ...                 Berlin-Est      1986-06-18
136   200_mètres_nage_libre  Femme  ...                       Rome       1994-09-6
137   200_mètres_nage_libre  Femme  ...                     Berlin       2002-08-3
138   200_mètres_nage_libre  Femme  ...                  Melbourne      2007-03-27
139   200_mètres_nage_libre  Femme  ...                  Melbourne      2007-03-28
140   200_mètres_nage_libre  Femme  ...                      Pékin      2008-08-11
141   200_mètres_nage_libre  Femme  ...                      Pékin      2008-08-13
142   200_mètres_nage_libre  Femme  ...                   Riccione       2009-03-8
143   200_mètres_nage_libre  Femme  ...                       Rome      2009-07-28
144   200_mètres_nage_libre  Femme  ...                       Rome      2009-07-29
145   200_mètres_nage_libre  Femme  ...                      Brême       1976-03-6
146   200_mètres_nage_libre  Femme  ...                    Beijing    janvier 1993
147   200_mètres_nage_libre  Femme  ...                                       1995
148   200_mètres_nage_libre  Femme  ...                   Göteborg      1997-04-18
149   200_mètres_nage_libre  Femme  ...                     Moscou       2002-04-7
150   200_mètres_nage_libre  Femme  ...                     Sydney      2005-11-19
151   200_mètres_nage_libre  Femme  ...                     Angers       2008-12-6
152   200_mètres_nage_libre  Femme  ...                     Rijeka      2008-12-14
153   200_mètres_nage_libre  Femme  ...                   Istanbul      2009-12-13
154   200_mètres_nage_libre  Femme  ...                       Doha       2014-12-7
155   400_mètres_nage_libre  Femme  ...                   New York      1919-08-16
156   400_mètres_nage_libre  Femme  ...                      Leeds      1921-07-29
157   400_mètres_nage_libre  Femme  ...               Indianapolis       1922-08-4
158   400_mètres_nage_libre  Femme  ...               Coral Gables      1927-01-23
159   400_mètres_nage_libre  Femme  ...                   New York      1928-06-30
160   400_mètres_nage_libre  Femme  ...                  Amsterdam       1928-08-6
161   400_mètres_nage_libre  Femme  ...                     Vienne      1928-08-27
162   400_mètres_nage_libre  Femme  ...                    Seattle       1931-02-3
163   400_mètres_nage_libre  Femme  ...                Los Angeles      1932-08-13
164   400_mètres_nage_libre  Femme  ...                  Rotterdam      1934-07-12
165   400_mètres_nage_libre  Femme  ...                 Copenhague      1937-02-10
166   400_mètres_nage_libre  Femme  ...                       Gand       1937-10-3
167   400_mètres_nage_libre  Femme  ...                 Magdebourg      1937-11-14
168   400_mètres_nage_libre  Femme  ...                 Copenhague      1937-12-12
169   400_mètres_nage_libre  Femme  ...                 Copenhague      1938-01-16
170   400_mètres_nage_libre  Femme  ...                 Copenhague       1938-08-1
171   400_mètres_nage_libre  Femme  ...                  Svendborg       1938-09-8
172   400_mètres_nage_libre  Femme  ...                 Copenhague      1940-09-15
173   400_mètres_nage_libre  Femme  ...                 Townsville      1956-08-25
174   400_mètres_nage_libre  Femme  ...                     Sydney      1956-10-20
175   400_mètres_nage_libre  Femme  ...                     Sydney       1960-09-9
176   400_mètres_nage_libre  Femme  ...                    Détroit       1960-08-5
177   400_mètres_nage_libre  Femme  ...                  Los Altos      1964-07-11
178   400_mètres_nage_libre  Femme  ...                  Los Altos       1964-08-1
179   400_mètres_nage_libre  Femme  ...                   New York      1964-08-31
180   400_mètres_nage_libre  Femme  ...                     Maumee      1965-08-14
181   400_mètres_nage_libre  Femme  ...                     Monaco      1965-08-26
182   400_mètres_nage_libre  Femme  ...            Fort Lauderdale      1967-06-30
183   400_mètres_nage_libre  Femme  ...                Santa Clara       1967-07-7
184   400_mètres_nage_libre  Femme  ...                   Winnipeg      1967-07-27
185   400_mètres_nage_libre  Femme  ...               Philadelphie      1967-08-18
186   400_mètres_nage_libre  Femme  ...                    Lincoln       1968-08-1
187   400_mètres_nage_libre  Femme  ...                Los Angeles      1968-08-25
188   400_mètres_nage_libre  Femme  ...                Los Angeles      1970-08-20
189   400_mètres_nage_libre  Femme  ...                    Londres      1971-04-30
190   400_mètres_nage_libre  Femme  ...                Santa Clara       1971-07-9
191   400_mètres_nage_libre  Femme  ...                     Munich      1972-08-30
192   400_mètres_nage_libre  Femme  ...                 Louisville      1973-08-22
193   400_mètres_nage_libre  Femme  ...                Santa Clara      1974-06-28
194   400_mètres_nage_libre  Femme  ...                    Concord      1974-08-22
195   400_mètres_nage_libre  Femme  ...                 Long Beach      1975-06-20
196   400_mètres_nage_libre  Femme  ...                 Berlin-Est       1976-06-3
197   400_mètres_nage_libre  Femme  ...                   Montréal      1976-07-20
198   400_mètres_nage_libre  Femme  ...                  Jönköping      1977-08-17
199   400_mètres_nage_libre  Femme  ...              The Woodlands       1978-08-2
200   400_mètres_nage_libre  Femme  ...               Berlin-Ouest      1978-08-24
201   400_mètres_nage_libre  Femme  ...                    Orlando      1987-12-20
202   400_mètres_nage_libre  Femme  ...                      Séoul      1988-09-22
203   400_mètres_nage_libre  Femme  ...                      Tours      2006-05-12
204   400_mètres_nage_libre  Femme  ...                   Budapest       2006-08-6
205   400_mètres_nage_libre  Femme  ...                  Eindhoven      2008-03-24
206   400_mètres_nage_libre  Femme  ...                  Sheffield      2009-03-16
207   400_mètres_nage_libre  Femme  ...                    Pescara      2009-06-27
208   400_mètres_nage_libre  Femme  ...                       Rome      2009-07-26
209   400_mètres_nage_libre  Femme  ...                     Irvine       2014-08-9
210   400_mètres_nage_libre  Femme  ...                 Gold Coast      2014-08-23
211   400_mètres_nage_libre  Femme  ...             Rio de Janeiro       2016-08-7
212   400_mètres_nage_libre  Femme  ...                       Bonn       1987-02-8
213   400_mètres_nage_libre  Femme  ...                   Göteborg      1997-04-18
214   400_mètres_nage_libre  Femme  ...                     Berlin      2003-01-26
215   400_mètres_nage_libre  Femme  ...                    Trieste      2005-12-10
216   400_mètres_nage_libre  Femme  ...                   Helsinki       2006-12-9
217   400_mètres_nage_libre  Femme  ...                      Leeds       2009-08-8
218   400_mètres_nage_libre  Femme  ...                   Chartres      2012-11-24
219   400_mètres_nage_libre  Femme  ...                     Berlin      2013-08-11
220   400_mètres_nage_libre  Femme  ...                   Hangzhou      2018-12-14
221   800_mètres_nage_libre  Femme  ...               Indianapolis      1919-08-17
222   800_mètres_nage_libre  Femme  ...                    Détroit       1925-08-6
223   800_mètres_nage_libre  Femme  ...               Indianapolis      1925-08-15
224   800_mètres_nage_libre  Femme  ...               Philadelphie       1926-08-7
225   800_mètres_nage_libre  Femme  ...                 Massapequa      1927-07-31
226   800_mètres_nage_libre  Femme  ...                   Honolulu      1929-08-10
227   800_mètres_nage_libre  Femme  ...                 Long Beach       1930-07-6
228   800_mètres_nage_libre  Femme  ...            Manhattan Beach      1935-07-21
229   800_mètres_nage_libre  Femme  ...                 Copenhague       1936-07-3
230   800_mètres_nage_libre  Femme  ...                 Copenhague      1941-08-13
231   800_mètres_nage_libre  Femme  ...                   Budapest      1953-06-28
232   800_mètres_nage_libre  Femme  ...                     Sydney      1956-01-14
233   800_mètres_nage_libre  Femme  ...                     Durban      1957-02-16
234   800_mètres_nage_libre  Femme  ...                     Sydney       1958-01-9
235   800_mètres_nage_libre  Femme  ...                  Melbourne      1958-02-20
236   800_mètres_nage_libre  Femme  ...                 Townsville      1958-06-13
237   800_mètres_nage_libre  Femme  ...                     Hobart      1959-02-19
238   800_mètres_nage_libre  Femme  ...                    Uppsala      1960-08-17

In [81]:
df["Date"][935] = '1983-01-01'
df["Date"][146] = '1993-01-01'
df["Date"][147] = '1995-01-01'
df["Date"][356] = '2009-01-01'
df["Date"][417]='2013-11-10'
df["Date"][457]='1981-01-01'
df["Date"][522]='1981-01-01'
df["Date"][523]='1982-01-01'
df["Date"][524]='1993-01-01'
df["Date"][525]='1993-01-01'
df["Date"][526]='1995-01-01'
df["Date"][528]='2001-01-01'
df["Date"][530]='2003-01-01'
df["Date"][535]='2013-12-13'
df["Date"][618]='1995-01-01'
df["Date"][620]='1995-01-01'
df["Date"][684]='1995-09-01'
df["Date"][866]='2017-07-25'

In [82]:
df = df.drop(labels=[521,868], axis=0)

In [83]:
#Export en csv
from google.colab import files
df.to_csv('SwimmingRecordsDatasetFemale.csv', sep='\t')
files.download('SwimmingRecordsDatasetFemale.csv')