<a href="https://colab.research.google.com/github/Aubinrocky/SwimmingRecords/blob/main/SwimmingRecordsScraping2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Importation des modules
import requests
from bs4 import BeautifulSoup
import pandas as pd
import random
import time
import matplotlib.pyplot as plt
headers = {'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/37.0.2062.94 Chrome/37.0.2062.94 Safari/537.36'}

In [ ]:
disciplines = ['50_mètres_nage_libre', '100_mètres_nage_libre','200_mètres_nage_libre','400_mètres_nage_libre','1500_mètres_nage_libre',
               '50_mètres_dos','100_mètres_dos','200_mètres_dos',
               '50_mètres_brasse','100_mètres_brasse','200_mètres_brasse',
               '50_mètres_papillon','100_mètres_papillon','200_mètres_papillon',
               '200_mètres_4_nages','400_mètres_4_nages']

In [ ]:
dataset = []
for discipline in disciplines:
  time.sleep(0.8)
  url = 'https://fr.wikipedia.org/wiki/Record_du_monde_de_natation_messieurs_du_' + discipline
  response = requests.get(url, headers=headers)
  soup = BeautifulSoup(response.content, 'lxml')
  divs = soup.find_all("div", {"class":"mw-body-content mw-content-ltr"})
  div = divs[0]
  spans = div.find_all("span", {"class":"mw-headline"})
  tables = div.find_all("table", {"class" : "wikitable sortable"})
  
  #Bassin de 50 mètres
  trs50 = tables[0].tbody.find_all("tr")
  trs50.pop(0)
  for tr in trs50:
    ligne = []
    tds = tr.find_all("td")
    for td in tds:
      ligne.append(td.getText())
    dataset.append([discipline,"Homme","50"]+ligne)
  #Bassin de 25 mètres
  trs25 = tables[1].tbody.find_all("tr")
  trs25.pop(0)
  for tr in trs25:
    ligne = []
    tds = tr.find_all("td")
    for td in tds:
      ligne.append(td.getText())
    dataset.append([discipline,"Homme","25"]+ligne)

In [ ]:
#Cas particulier du 800m où le tableau n'est pas le même:
time.sleep(0.8)
url = 'https://fr.wikipedia.org/wiki/Record_du_monde_de_natation_messieurs_du_800_m%C3%A8tres_nage_libre'
response = requests.get(url, headers=headers)
soup = BeautifulSoup(response.content, 'lxml')
divs = soup.find_all("div", {"class":"mw-body-content mw-content-ltr"})
div = divs[0]
spans = div.find_all("span", {"class":"mw-headline"})
tables = div.find_all("table", {"class" : "wikitable sortable"})

#Bassin de 50 mètres
trs50 = tables[0].tbody.find_all("tr")
trs50.pop(0)
for tr in trs50:
  ligne = []
  tds = tr.find_all("td")
  for td in tds:
    ligne.append(td.getText())
  if len(ligne)==6:
    dataset.append(["800_mètres_nage_libre","Homme","50", ligne[0], ligne[1], None, None, ligne[2], ligne[3],ligne[4],ligne[5]])
#Bassin de 25 mètres
trs25 = tables[1].tbody.find_all("tr")
trs25.pop(0)
for tr in trs25:
  ligne = []
  tds = tr.find_all("td")
  for td in tds:
    ligne.append(td.getText())
  dataset.append(["800_mètres_nage_libre","Homme","25"]+ligne)

In [ ]:
#On retire les lignes de non record (intrus du tableau)
for i in range (len(dataset)):
  if len(dataset[i])==4 or len(dataset[i])==10:
    dataset.pop(i)

In [ ]:
#Mise en forme de l'age, la nationalité, la competition, le lieu et la date :
for row in dataset:
  if row[6]!= None:
    row[6] = row[6].split('\n')[0]
  row[7] = row[7].split('\n')[0]
  row[8] = row[8].split('\n')[0]
  row[9] = row[9].split('\n')[0]
  row[10] = row[10].split('\n')[0]

In [ ]:
#Mise en forme de la date I/II
for row in dataset:
  date_prov = row[10].split(" ")
  try:
    if date_prov[1] == 'janvier':
        row[10] = date_prov[2]+'-'+'01'+'-'+ date_prov[0]
    if date_prov[1] == 'février':
        row[10] = date_prov[2]+'-'+'02'+'-'+ date_prov[0]
    if date_prov[1] == 'mars':
        row[10] = date_prov[2]+'-'+'03'+'-'+ date_prov[0]
    if date_prov[1] == 'avril':
        row[10] = date_prov[2]+'-'+'04'+'-'+ date_prov[0]
    if date_prov[1] == 'mai':
        row[10] = date_prov[2]+'-'+'05'+'-'+ date_prov[0]
    if date_prov[1] == 'juin':
        row[10] = date_prov[2]+'-'+'06'+'-'+ date_prov[0]
    if date_prov[1] == 'juillet':
        row[10] = date_prov[2]+'-'+'07'+'-'+ date_prov[0]
    if date_prov[1] == 'août':
        row[10] = date_prov[2]+'-'+'08'+'-'+ date_prov[0]
    if date_prov[1] == 'septembre':
        row[10] = date_prov[2]+'-'+'09'+'-'+ date_prov[0]
    if date_prov[1] == 'octobre':
        row[10] = date_prov[2]+'-'+'10'+'-'+ date_prov[0]
    if date_prov[1] == 'novembre':
        row[10] = date_prov[2]+'-'+'11'+'-'+ date_prov[0]
    if date_prov[1] == 'décembre':
        row[10] = date_prov[2]+'-'+'12'+'-'+ date_prov[0]
  except:
    print(row)

#Mise en forme de la date II/II
for row in dataset:
  if 'février' in row[-1]:
    row[-1]=row[-1].split('février ')[1]
    
  if '1er' in row[-1]:
    row[-1]=row[-1].split('1er')[0]+ '1'

for row in dataset:
  if '1er' in row[-1]:
    row[-1]=row[-1].split('1er')[0]+ '1'

In [ ]:
#Mise en forme du temps
for row in dataset:
  if len(row[3].split('\n'))!=2:
    row[3]=row[3].split('\n')[1]+'\n'

for row in dataset:
  row[3]= row[3].split('\n')[0]

for row in dataset:
  if len(row[3].split('['))!=1:
    row[3]=row[3].split('[')[0]

for row in dataset:
  row[3]=row[3].split('(')[0]

for row in dataset:
  if len(row[3].split('min'))==2:
    row[3]=row[3].split(' min ')[0]+':'+row[3].split(' min ')[1]
  
  if len(row[3].split(' s '))==2:
    row[3]=row[3].split(' s ')[0]+':'+row[3].split(' s ')[1]

In [ ]:
#Dernières modifications:
dataset[247][-1]='1981-01-01'
dataset[248][-1]='1981-01-01'
dataset[400][-1]='1910-01-01'
dataset[751][-1]='1959-07-01'
dataset[799][-1]='1981-01-01'
dataset[801][-1]='1985-01-01'
dataset[803][-1]='1992-01-01'
dataset[804][-1]='1993-01-01'
dataset[805][-1]='1993-01-01'
dataset[806][-1]='1993-01-01'
dataset[808][-1]='1997-01-01'
dataset[865][-1]='2008-08-15'
dataset[998][-1]='1982-01-01'
dataset[1002][-1]='1985-01-01'

In [ ]:
for i in range(len(dataset)):
  if '---' in dataset[i][3]:
    dataset.pop(i)
  if len(dataset[i][3])==0:
    dataset.pop(i)

In [ ]:
pd.set_option('display.max_rows', None)
df = pd.DataFrame(dataset, columns = ["Discipline", "Sexe", "Bassin (m)","Temps", "Nom", "Naissance", "Age", "Nationalite", "Competition", "Lieu", "Date"])
del df["Competition"]
del df["Nom"]
del df["Naissance"]
df

                 Discipline   Sexe  ...                    Lieu           Date
0      50_mètres_nage_libre  Homme  ...            Philadelphie     1976-08-14
1      50_mètres_nage_libre  Homme  ...               Etobicoke      1977-07-3
2      50_mètres_nage_libre  Homme  ...                   Miami     1978-07-29
3      50_mètres_nage_libre  Homme  ...     Fribourg-en-Brisgau     1979-07-23
4      50_mètres_nage_libre  Homme  ...               Amersfoot      1980-02-2
5      50_mètres_nage_libre  Homme  ...                  Austin     1980-04-10
6      50_mètres_nage_libre  Homme  ...                Honolulu     1980-08-15
7      50_mètres_nage_libre  Homme  ...                Honolulu     1980-08-15
8      50_mètres_nage_libre  Homme  ...              Brown Deer     1981-08-15
9      50_mètres_nage_libre  Homme  ...              Bellinzone     1985-07-21
10     50_mètres_nage_libre  Homme  ...                  Austin      1985-12-6
11     50_mètres_nage_libre  Homme  ...                 Orlando     1986-06-26
12     50_mètres_nage_libre  Homme  ...                  Clovis     1987-07-30
13     50_mètres_nage_libre  Homme  ...                Brisbane     1987-08-13
14     50_mètres_nage_libre  Homme  ...                 Orlando     1988-03-25
15     50_mètres_nage_libre  Homme  ...            Indianapolis     1988-04-10
16     50_mètres_nage_libre  Homme  ...                   Séoul     1988-09-24
17     50_mètres_nage_libre  Homme  ...                   Tokyo     1989-08-20
18     50_mètres_nage_libre  Homme  ...               Nashville     1990-03-24
19     50_mètres_nage_libre  Homme  ...               Nashville     1990-03-24
20     50_mètres_nage_libre  Homme  ...                  Moscou     2000-06-16
21     50_mètres_nage_libre  Homme  ...                  Sydney     2008-02-17
22     50_mètres_nage_libre  Homme  ...               Eindhoven     2008-03-23
23     50_mètres_nage_libre  Homme  ...                  Sydney     2008-03-27
24     50_mètres_nage_libre  Homme  ...                  Sydney     2008-03-28
25     50_mètres_nage_libre  Homme  ...             Montpellier     2009-04-26
26     50_mètres_nage_libre  Homme  ...               São Paulo     2009-12-18
27     50_mètres_nage_libre  Homme  ...                  Dallas     1992-03-24
28     50_mètres_nage_libre  Homme  ...               Sheffield     1993-02-17
29     50_mètres_nage_libre  Homme  ...     Desenzano del Garda     1994-03-13
30     50_mètres_nage_libre  Homme  ...               Sheffield     1998-12-13
31     50_mètres_nage_libre  Homme  ...               Sheffield     1998-12-13
32     50_mètres_nage_libre  Homme  ...             Minneapolis     2000-03-23
33     50_mètres_nage_libre  Homme  ...             Minneapolis     2000-03-23
34     50_mètres_nage_libre  Homme  ...             Minneapolis     2000-03-23
35     50_mètres_nage_libre  Homme  ...                   Paris     2001-01-28
36     50_mètres_nage_libre  Homme  ...             Long Island     2004-03-25
37     50_mètres_nage_libre  Homme  ...                Hambourg     2006-08-13
38     50_mètres_nage_libre  Homme  ...                  Berlin     2007-11-18
39     50_mètres_nage_libre  Homme  ...              Manchester     2008-04-11
40     50_mètres_nage_libre  Homme  ...            Johannesburg      2008-09-6
41     50_mètres_nage_libre  Homme  ...                  Rijeka     2008-12-11
42     50_mètres_nage_libre  Homme  ...        Pietermaritzburg      2009-08-8
43     50_mètres_nage_libre  Homme  ...                    Doha      2014-12-5
44     50_mètres_nage_libre  Homme  ...               Las Vegas     2019-12-20
45     50_mètres_nage_libre  Homme  ...                Budapest     2020-11-21
46    100_mètres_nage_libre  Homme  ...                  Vienne      1905-12-3
47    100_mètres_nage_libre  Homme  ...                 Londres     1908-07-20
48    100_mètres_nage_libre  Homme  ...                New York     1910-04-15
49    100_mètres_nage_libre  Homme  ...               Bruxelles      1912-04-6
50    100_mètres_nage_libre  Homme  ...         Suède Stockholm      1912-07-6
51    100_mètres_nage_libre  Homme  ...                Hambourg     1912-07-20
52    100_mètres_nage_libre  Homme  ...                New York      1918-08-9
53    100_mètres_nage_libre  Homme  ...                  Anvers     1920-08-24
54    100_mètres_nage_libre  Homme  ...                 Alameda     1922-07-19
55    100_mètres_nage_libre  Homme  ...                   Miami     1924-02-17
56    100_mètres_nage_libre  Homme  ...               New Haven      1934-03-2
57    100_mètres_nage_libre  Homme  ...               New Haven      1935-03-5
58    100_mètres_nage_libre  Homme  ...               New Haven     1936-02-11
59    100_mètres_nage_libre  Homme  ...               New Haven     1944-04-13
60    100_mètres_nage_libre  Homme  ...                  Menton     1947-09-15
61    100_mètres_nage_libre  Homme  ...               New Haven     1948-06-29
62    100_mètres_nage_libre  Homme  ...               New Haven      1954-04-1
63    100_mètres_nage_libre  Homme  ...               Melbourne     1956-11-30
64    100_mètres_nage_libre  Homme  ...                  Sydney     1957-01-19
65    100_mètres_nage_libre  Homme  ...                Brisbane     1957-01-28
66    100_mètres_nage_libre  Homme  ...                Budapest     1961-08-18
67    100_mètres_nage_libre  Homme  ...          Rio de Janeiro     1961-09-20
68    100_mètres_nage_libre  Homme  ...                Budapest     1964-09-13
69    100_mètres_nage_libre  Homme  ...                   Tokyo     1964-10-14
70    100_mètres_nage_libre  Homme  ...                Winnipeg     1967-07-27
71    100_mètres_nage_libre  Homme  ...             Los Angeles      1968-09-2
72    100_mètres_nage_libre  Homme  ...                  Mexico     1968-10-19
73    100_mètres_nage_libre  Homme  ...                 Chicago     1970-08-23
74    100_mètres_nage_libre  Homme  ...                 Chicago      1972-08-5
75    100_mètres_nage_libre  Homme  ...                  Munich      1972-09-3
76    100_mètres_nage_libre  Homme  ...              Long Beach     1975-06-21
77    100_mètres_nage_libre  Homme  ...         Fort Lauderdale      1975-08-3
78    100_mètres_nage_libre  Homme  ...             Kansas City     1975-08-23
79    100_mètres_nage_libre  Homme  ...                Montréal     1976-07-24
80    100_mètres_nage_libre  Homme  ...                Montréal     1976-07-25
81    100_mètres_nage_libre  Homme  ...            Philadelphie     1976-08-14
82    100_mètres_nage_libre  Homme  ...                  Austin      1981-04-3
83    100_mètres_nage_libre  Homme  ...           Mission Viejo      1985-08-6
84    100_mètres_nage_libre  Homme  ...           Mission Viejo      1985-08-6
85    100_mètres_nage_libre  Homme  ...                 Orlando     1986-06-24
86    100_mètres_nage_libre  Homme  ...                  Austin     1988-08-10
87    100_mètres_nage_libre  Homme  ...                  Monaco     1994-06-18
88    100_mètres_nage_libre  Homme  ...                  Sydney     2000-09-16
89    100_mètres_nage_libre  Homme  ...                  Sydney     2000-09-19
90    100_mètres_nage_libre  Homme  ...               Eindhoven     2008-03-21
91    100_mètres_nage_libre  Homme  ...               Eindhoven     2008-03-22
92    100_mètres_nage_libre  Homme  ...                   Pékin     2008-08-11
93    100_mètres_nage_libre  Homme  ...                   Pékin     2008-08-13
94    100_mètres_nage_libre  Homme  ...                   Pékin     2008-08-13
95    100_mètres_nage_libre  Homme  ...             Montpellier     2009-04-23
96    100_mètres_nage_libre  Homme  ...                    Rome  2009[8]-07-30
97    100_mètres_nage_libre  Homme  ...                   Tokyo     1985-08-17
98    100_mètres_nage_libre  Homme  ...                  Berlin     2002-07-29
99    100_mètres_nage_libre  Homme  ...               Barcelone     2003-07-27
100   100_mètres_nage_libre  Homme  ...                   Pékin     2008-08-11
101   200_mètres_nage_libre  Homme  ...           Weston-s-Mare     1902-08-18
102   200_mètres_nage_libre  Homme  ...                Budapest     1908-06-28
103   200_mètres_nage_libre  Homme  ...              Pittsburgh     1909-03-26
104   200_mètres_nage_libre  Homme  ...           San Francisco     1916-11-24
105   200_mètres_nage_libre  Homme  ...                 Détroit     1920-04-10
106   200_mètres_nage_libre  Homme  ...                Honolulu     1922-05-26
107   200_mètres_nage_libre  Homme  ...              McKeesport      1925-12-9
108   200_mètres_nage_libre  Homme  ...               Ann Arbor      1927-04-5
109   200_mètres_nage_libre  Homme  ...                 Chicago     1935-04-12
110   200_mètres_nage_libre  Homme  ...                Columbus     1944-02-12
111   200_mètres_nage_libre  Homme  ...               Marseille     1946-09-20
112   200_mètres_nage_libre  Homme  ...               New Haven     1950-03-31
113   200_mètres_nage_libre  Homme  ...                Columbus     1954-02-27
114   200_mètres_nage_libre  Homme  ...                Columbus      1955-03-8
115   200_mètres_nage_libre  Homme  ...             Minneapolis      1957-03-8
116   200_mètres_nage_libre  Homme  ...                  Sydney     1958-01-18
117   200_mètres_nage_libre  Homme  ...                  Sydney      1958-03-5
118   200_mètres_nage_libre  Homme  ...                   Osaka     1958-08-22
119   200_mètres_nage_libre  Homme  ...                  Sydney     1959-01-16
120   200_mètres_nage_libre  Homme  ...                   Osaka     1959-07-26
121   200_mètres_nage_libre  Homme  ...                   Osaka     1961-06-24
122   200_mètres_nage_libre  Homme  ...                   Tokyo      1961-08-6
123   200_mètres_nage_libre  Homme  ...             Los Angeles      1961-08-2
124   200_mètres_nage_libre  Homme  ...                   Tokyo     1963-08-13
125   200_mètres_nage_libre  Homme  ...             Los Angeles     1963-07-27
126   200_mètres_nage_libre  Homme  ...                   Tokyo     1963-04-21
127   200_mètres_nage_libre  Homme  ...                   Osaka     1963-08-24
128   200_mètres_nage_libre  Homme  ...                Dortmund     1964-05-24
129   200_mètres_nage_libre  Homme  ...               Los Altos      1964-08-1
130   200_mètres_nage_libre  Homme  ...             Los Angeles     1966-07-29
131   200_mètres_nage_libre  Homme  ...                 Lincoln     1966-08-19
132   200_mètres_nage_libre  Homme  ...                Winnipeg     1967-07-29
133   200_mètres_nage_libre  Homme  ...                Oak Park     1967-08-12
134   200_mètres_nage_libre  Homme  ...              Long Beach     1968-08-30
135   200_mètres_nage_libre  Homme  ...              Long Beach     1968-08-30
136   200_mètres_nage_libre  Homme  ...             Santa Clara     1969-07-12
137   200_mètres_nage_libre  Homme  ...                 Leipzig      1971-09-4
138   200_mètres_nage_libre  Homme  ...                   Minsk     1971-09-10
139   200_mètres_nage_libre  Homme  ...                  Munich     1972-08-29
140   200_mètres_nage_libre  Homme  ...                 Concord     1974-08-23
141   200_mètres_nage_libre  Homme  ...              Long Beach     1975-06-18
142   200_mètres_nage_libre  Homme  ...              Long Beach     1975-06-18
143   200_mètres_nage_libre  Homme  ...             Kansas City     1975-08-21
144   200_mètres_nage_libre  Homme  ...                Montréal     1976-07-19
145   200_mètres_nage_libre  Homme  ...                 Potsdam      1979-04-7
146   200_mètres_nage_libre  Homme  ...                  Austin     1980-04-10
147   200_mètres_nage_libre  Homme  ...           Mission Viejo     1982-07-19
148   200_mètres_nage_libre  Homme  ...                 Hanovre     1983-06-21
149   200_mètres_nage_libre  Homme  ...                    Rome     1983-08-22
150   200_mètres_nage_libre  Homme  ...                  Munich      1984-06-8
151   200_mètres_nage_libre  Homme  ...             Los Angeles     1984-07-29
152   200_mètres_nage_libre  Homme  ...                   Séoul     1988-09-19
153   200_mètres_nage_libre  Homme  ...                    Bonn     1989-08-15
154   200_mètres_nage_libre  Homme  ...                Brisbane     1999-03-23
155   200_mètres_nage_libre  Homme  ...                  Sydney     1999-08-23
156   200_mètres_nage_libre  Homme  ...                  Sydney     1999-08-24
157   200_mètres_nage_libre  Homme  ...                  Sydney     2000-05-14
158   200_mètres_nage_libre  Homme  ...                  Sydney     2000-05-15
159   200_mètres_nage_libre  Homme  ...                  Sydney     2000-09-17
160   200_mètres_nage_libre  Homme  ...                  Sydney     2000-09-18
161   200_mètres_nage_libre  Homme  ...                  Hobart     2001-03-27
162   200_mètres_nage_libre  Homme  ...                 Fukuoka     2001-07-25
163   200_mètres_nage_libre  Homme  ...               Melbourne     2007-03-27
164   200_mètres_nage_libre  Homme  ...                   Pékin     2008-08-12
165   200_mètres_nage_libre  Homme  ...                    Rome     2009-07-28
166   200_mètres_nage_libre  Homme  ...                 Fukuoka     2001-07-27
167   200_mètres_nage_libre  Homme  ...                   Pékin     2008-08-13
168   200_mètres_nage_libre  Homme  ...                 Londres      2012-08-1
169   200_mètres_nage_libre  Homme  ...                 Londres      2012-08-1
170   200_mètres_nage_libre  Homme  ...               Barcelone      2013-08-2
171   400_mètres_nage_libre  Homme  ...                 Londres     1908-07-16
172   400_mètres_nage_libre  Homme  ...                Seacombe      1908-10-2
173   400_mètres_nage_libre  Homme  ...                Budapest      1910-06-8
174   400_mètres_nage_libre  Homme  ...                 Londres     1912-09-26
175   400_mètres_nage_libre  Homme  ...             Los Angeles      1919-10-9
176   400_mètres_nage_libre  Homme  ...          Brighton Beach     1921-09-25
177   400_mètres_nage_libre  Homme  ...               Stockholm     1922-06-22
178   400_mètres_nage_libre  Homme  ...                Honolulu     1922-06-22
179   400_mètres_nage_libre  Homme  ...               New Haven      1923-03-6
180   400_mètres_nage_libre  Homme  ...               Stockholm      1923-12-9
181   400_mètres_nage_libre  Homme  ...               Stockholm     1925-09-11
182   400_mètres_nage_libre  Homme  ...                   Paris     1931-04-16
183   400_mètres_nage_libre  Homme  ...                   Tokyo     1933-08-14
184   400_mètres_nage_libre  Homme  ...                Honolulu     1934-08-30
185   400_mètres_nage_libre  Homme  ...                Honolulu     1941-05-13
186   400_mètres_nage_libre  Homme  ...             Monte-Carlo     1947-09-12
187   400_mètres_nage_libre  Homme  ...                   Tokyo     1949-07-24
188   400_mètres_nage_libre  Homme  ...             Los Angeles     1949-08-18
189   400_mètres_nage_libre  Homme  ...               New Haven     1950-03-11
190   400_mètres_nage_libre  Homme  ...               New Haven      1950-04-1
191   400_mètres_nage_libre  Homme  ...               New Haven     1951-03-24
192   400_mètres_nage_libre  Homme  ...               New Haven      1954-04-3
193   400_mètres_nage_libre  Homme  ...                  Sydney     1958-01-15
194   400_mètres_nage_libre  Homme  ...               Melbourne     1957-01-12
195   400_mètres_nage_libre  Homme  ...                  Sydney      1959-02-7
196   400_mètres_nage_libre  Homme  ...                   Osaka     1959-07-26
197   400_mètres_nage_libre  Homme  ...                  Sydney     1960-02-23
198   400_mètres_nage_libre  Homme  ...                 Chicago     1962-08-17
199   400_mètres_nage_libre  Homme  ...               Los Altos     1964-07-31
200   400_mètres_nage_libre  Homme  ...                   Tokyo     1964-10-15
201   400_mètres_nage_libre  Homme  ...                 Lincoln     1966-08-18
202   400_mètres_nage_libre  Homme  ...                 Lincoln     1966-08-18
203   400_mètres_nage_libre  Homme  ...                 Utrecht     1966-08-25
204   400_mètres_nage_libre  Homme  ...                 Haywood     1967-06-25
205   400_mètres_nage_libre  Homme  ...                  Monaco      1967-07-2
206   400_mètres_nage_libre  Homme  ...                  Monaco      1967-07-4
207   400_mètres_nage_libre  Homme  ...             Santa Clara      1967-07-7
208   400_mètres_nage_libre  Homme  ...                   Tokyo     1967-08-28
209   400_mètres_nage_libre  Homme  ...                 Haywood     1968-06-23
210   400_mètres_nage_libre  Homme  ...                 Lincoln      1968-08-1
211   400_mètres_nage_libre  Homme  ...              Louisville     1969-08-14
212   400_mètres_nage_libre  Homme  ...             Los Angeles     1970-08-20
213   400_mètres_nage_libre  Homme  ...               Barcelone      1970-09-7
214   400_mètres_nage_libre  Homme  ...                 Houston     1971-08-25
215   400_mètres_nage_libre  Homme  ...                Brisbane     1972-02-12
216   400_mètres_nage_libre  Homme  ...                 Chicago      1972-08-4
217   400_mètres_nage_libre  Homme  ...                Belgrade      1973-09-6
218   400_mètres_nage_libre  Homme  ...                 Concord     1974-08-22
219   400_mètres_nage_libre  Homme  ...                 Concord     1974-08-22
220   400_mètres_nage_libre  Homme  ...              Long Beach     1975-06-19
221   400_mètres_nage_libre  Homme  ...             Kansas City     1975-08-20
222   400_mètres_nage_libre  Homme  ...              Long Beach     1976-06-18
223   400_mètres_nage_libre  Homme  ...                Montréal     1976-07-22
224   400_mètres_nage_libre  Homme  ...              Berlin-Est     1977-08-27
225   400_mètres_nage_libre  Homme  ...                 Potsdam      1979-04-6
226   400_mètres_nage_libre  Homme  ...                  Moscou     1979-08-19
227   400_mètres_nage_libre  Homme  ...                 Potsdam     1980-02-29
228   400_mètres_nage_libre  Homme  ...               Etobicoke     1980-07-15
229   400_mètres_nage_libre  Homme  ...                  Moscou     1982-03-12
230   400_mètres_nage_libre  Homme  ...                    Kiev     1982-07-19
231   400_mètres_nage_libre  Homme  ...                  Moscou     1983-02-19
232   400_mètres_nage_libre  Homme  ...               Remscheid     1985-06-27
233   400_mètres_nage_libre  Homme  ...                 Orlando     1988-03-25
234   400_mètres_nage_libre  Homme  ...                   Séoul     1988-09-23
235   400_mètres_nage_libre  Homme  ...                Canberra      1992-04-3
236   400_mètres_nage_libre  Homme  ...               Barcelone     1992-07-29
237   400_mètres_nage_libre  Homme  ...                    Rome      1994-09-9
238   400_mètres_nage_libre  Homme  ...                  Sydney     1999-08-22
239   400_mètres_nage_libre  Homme  ...                  Sydney     2000-05-13
240   400_mètres_nage_libre  Homme  ...                  Sydney     2000-09-16
241   400_mètres_nage_libre  Homme  ...                 Fukuoka     2001-07-22
242   400_mètres_nage_libre  Homme  ...              Manchester     2002-07-30
243   400_mètres_nage_libre  Homme  ...                    Rome     2009-07-26
244   400_mètres_nage_libre  Homme  ...
245   400_mètres_nage_libre  Homme  ...                 Rostock     1981-01-01
246   400_mètres_nage_libre  Homme  ...                             1981-01-01
247   400_mètres_nage_libre  Homme  ...               Sheffield      1995-11-2
248   400_mètres_nage_libre  Homme  ...                  Sydney     1998-09-25
249   400_mètres_nage_libre  Homme  ...               Hong Kong      1999-04-2
250   400_mètres_nage_libre  Homme  ...                  Sydney     2002-07-18
251   400_mètres_nage_libre  Homme  ...                  Berlin     2009-11-14

In [ ]:
#Export en csv
from google.colab import files
df.to_csv('SwimmingRecordsDataset.csv', sep='\t')
files.download('SwimmingRecordsDataset.csv')